### ISSUE TITLE
[Feature Request] Respect Entity Permissions

### ISSUE THREAD

**Issue by patrickburk1988** [Daimakaicho/better-entity-link#1]
Very cool module. The only issue I'm running into is that the right-click context menu on entity links is available for all players, and players can activate any of the context menu options regardless of their permissions regarding that entity.

For example: I have a journal entry containing a link to a secret scene (`Navigation disabled, GM only`) and a link to a secret journal entry (`None` permissions). The player can bypass their lack of permissions by right-clicking the link and selecting `View Scene` and `Show Players (Text)`/`Show Players (Image)`.

**Comment by Daimakaicho** [comment]
Thanks for your feedback! All scenes options should be restricted to GM only, I'll look into this issue.

**Comment by Daimakaicho** [comment]
I did a test on my side and I can not reproduce this bug: contextmenu don't show up when user is a standard user.
Did you changed your players permissions in your campaign ? What role did you assign to your players ?

**Comment by patrickburk1988** [comment]
Thanks for taking a look at this so quickly!

My players all have standard player user roles. I have changed the permissions somewhat, though. The current settings are:
| Setting                       | Player Permission |
|-------------------------------|-------------------|
| Configure Token Settings      | Disabled          |
| Create Journal Entries        | Disabled          |
| Create Map Notes              | Disabled          |
| Create Measured Template      | Enabled           |
| Create New Actors             | Disabled          |
| Create New Items              | Disabled          |
| Create New Tokens             | Disabled          |
| Display Mouse Cursor          | Enabled           |
| Display Ruler Measurement     | Enabled           |
| Modify Configuration Settings | Disabled          |
| Open and Close Doors          | Disabled          |
| Upload New Files              | Disabled          |
| Use Drawing Tools             | Enabled           |
| Use File Browser              | Disabled          |
| Use Script Macros             | Enabled           |
| Whisper Private Messages      | Enabled           |

I'm using Forge to host my game. I don't know if it's pertinent to the issue at hand, but I _don't_ use Forge's automatic user management.

**Comment by Daimakaicho** [comment]
Okay, I find a bug related to action display conditions. I'm investigating this.

**Comment by Daimakaicho** [comment]
I released a new version (v1.0.1). Please update and try again. This version should solve your issue, but even if it do not, this is a mandatory update to dig deeper into you issue.

**Comment by patrickburk1988** [comment]
Scene links look to be fixed! Journal entry links with `None` permissions are still showing options for players to show text/images, though.

**Comment by Daimakaicho** [comment]
I released a new version (v1.0.2) which includes new controls around permission on all entities.

**Comment by patrickburk1988** [comment]
Works perfectly! Thanks!
